### ISSUE TITLE
Python Requires 3.9+

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [MaterializeInc/kubernetes-stubs#5]
Why does a python type stub package have a python requires [here](https://github.com/MaterializeInc/kubernetes-stubs/blob/b66f02cf0ab3c7e1b8e0cfab39c1d11d1dcf73cb/pyproject.toml#L15)? This line means that only python 3.9+ is able to install this package. But type stubs aren't used at runtime so they should be fine with lower versions. My current impact is I work on codebase that is 3.8 (some libraries we depend on are still only 3.8 support) so the requires being set to 3.9+ here blocks installing it normally.

**Comment by benesch** [comment]
I've paged out the details, but IIRC the type stubs use syntax that is only available in Python 3.9+.

**Comment by hmc-cs-mdrissi** [comment]
Type stubs are allowed to use syntax newer version of runtime. I use 3.9/3.10 syntax in stubs a lot while running 3.8. typeshed uses 3.10 syntax, but is commonly used with 3.6 still as mypy continues to support 3.6 even though it's eol and mypy bundles typeshed stubs.

In fact even non stub files are allowed to use newer syntax with `from __future__ import annotations`. Type stubs because they are only used by type checkers do not have to be compatible with runtime python version used and will continue to work.

edit: There is one caveat. I think mypy because it's python package requires you not use things that are a grammar error. But most new typing features aren't grammar errors. A | B is new typing 3.10 feature at runtime, but even in 3.6 is not a grammar error.  I'm unaware of any 3.9/3.10 typing grammar changes. I think 3.11 will have one for TypeVarTuple, but even that has a second equivalent form to support pre-3.11. For non python type checkers like pyright/pyre there's no restriction on grammar.

**Comment by benesch** [comment]
Ah, ok, I think that checks out for me. Want to submit a PR?

**Comment by hmc-cs-mdrissi** [comment]
Thank you for quick resolution.
